"""empty message

Revision ID: 008d898583d9
Revises: b5de0f742c83
Create Date: 2019-10-01 20:26:48.647556

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '008d898583d9'
down_revision = 'b5de0f742c83'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('order')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('order',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('order_name', sa.VARCHAR(length=100), nullable=False),
    sa.Column('order_creation_time', sa.DATETIME(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###
